# Generated by Django 6.0.1 on 2026-02-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True, verbose_name='Key')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Value')),
                ('expire_date', models.DateField(verbose_name='Expire date')),
                ('key_type', models.CharField(choices=[('email_confirm', 'Email confirmation'), ('forgot_passwrod', 'Password recover'), ('registeration', 'Registration')], max_length=20, verbose_name='Key type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User key',
                'verbose_name_plural': 'Users keys',
            },
        ),
    ]
